### PR TITLE
qgis-dev-0.9.0

### LINKED ISSUE #89: Spatialite 5.0.0
https://github.com/qgis/QGIS/issues/39120

### LINKED ISSUE #135: Support for LERC compression (libtiff >= 4.3 and GDAL >= 3.3)
I'm interested in using GeoTIFF data that have been generated using the LERC compression.
It seems that the lates QGIS version 3.20.0 (binary installer for Mac OSX) does not support this feature.

AFAIK the LERC compression requires libtiff >= 4.3 and GDAL >= 3.3, so I assume that it is not a QGIS limitation but just a matter of packaging.

What are plans to update libtiff/GDAL and support LERC compressed GeoTIFF data?

### LINKED ISSUE #138: do not ship cmake binary in qgis-deps
not necessary...

### PR DESCRIPTION
**Pull request by PeterPetrik**
fix #138
fix #135
fix #89

also updated proj to 8.x and bunch of other packages

### CODE REVIEW

**Comment by avalentino** [comment]
Thanks a lot @PeterPetrik for fixing this issue.

Sorry for the silly question but I am still not able to find the the recipe for liblerc in [2] and [2].
Is it indirectly included in some of the other packages?

[1] https://github.com/qgis/QGIS-Mac-Packager/tree/master/qgis_deps/recipes
[2] https://github.com/qgis/QGIS-Mac-Packager/tree/master/qgis_bundle/recipes

**Comment by PeterPetrik** [comment]
Not a silly question, I forgot to add it ...!

**Comment by avalentino** [comment]
@PeterPetrik do you think that there is still a chacne to have LERC in the next QGIS release?
Should we re-open #135?

**Comment by PeterPetrik** [comment]
I am on it

**Comment by PeterPetrik** [comment]
do you have some open-dataset available for me to test it? @avalentino

**Comment by avalentino** [comment]
@PeterPetrik no, but I can provide a simple script to convert an existing TIFF product (maybe one that you are already using for your tests) into a LERC encoded COG.
I could also generate it myself and share via "We Transfer" or services like that.
Just let me know what open-dataset you want to use as base for the conversion.

**Comment by PeterPetrik** [comment]
if you can send me any, ideally smaller-better. thanks!

**Comment by avalentino** [comment]
OK, will do in the afternoon

**Comment by avalentino** [comment]
Original product: https://github.com/OSGeo/gdal/blob/master/autotest/gcore/data/float32.tif

Th generate the LERC compressed COG ([float32-lerc.tif.zip](https://github.com/qgis/QGIS-Mac-Packager/files/7177617/float32-lerc.tif.zip)) I have used:

```sh
$ gdal_translate -OF COG -co COMPRESS=LERC_ZSTD -co MAX_Z_ERROR=1 float32.tif float32-lerc.tif
```

**Pull request merged**
